// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9tB_tOW2qxdUKU_JtfG4CfkMCHFbXFyU',
    appId: '1:166567297331:web:0dbc57e0ba7efe617b7e46',
    messagingSenderId: '166567297331',
    projectId: 'oceianescooter',
    authDomain: 'oceianescooter.firebaseapp.com',
    storageBucket: 'oceianescooter.appspot.com',
    measurementId: 'G-72TJN251PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdwSdwwF5icGCTrLebmifHqZhsZTSDfJ0',
    appId: '1:166567297331:android:518e4090fba19beb7b7e46',
    messagingSenderId: '166567297331',
    projectId: 'oceianescooter',
    storageBucket: 'oceianescooter.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKBcPYYUUX_IhlNkPXajGdnBdWOe3-zi0',
    appId: '1:166567297331:ios:d0283f56fe3e29cf7b7e46',
    messagingSenderId: '166567297331',
    projectId: 'oceianescooter',
    storageBucket: 'oceianescooter.appspot.com',
    iosBundleId: 'com.example.oceanViewEScooters',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9tB_tOW2qxdUKU_JtfG4CfkMCHFbXFyU',
    appId: '1:166567297331:web:b1fdf8e8a5b475c37b7e46',
    messagingSenderId: '166567297331',
    projectId: 'oceianescooter',
    authDomain: 'oceianescooter.firebaseapp.com',
    storageBucket: 'oceianescooter.appspot.com',
    measurementId: 'G-ST4DCYPKX6',
  );
}
